export const data = {
  results: [
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 2500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 2500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 3300,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 1500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 2547,
      newConstructionType: "BUILDER_SPEC",
      price: 2500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },
    {
      bathrooms: 1,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      imgSrc:
        "https://images.unsplash.com/photo-1565402170291-8491f14678db?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1117&q=80",
      livingArea: 550,
      lotAreaUnit: "sqft",
      lotAreaValue: 7000.092,
      price: 1500,
      state: "TX",
      streetAddress: "5021 Rietta St",
      zipcode: "77016",
      property: "villa",
    },
    {
      bathrooms: 2,
      bedrooms: 4,
      city: "Houston",
      country: "USA",
      currency: "USD",
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      imgSrc:
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
      livingArea: 550,
      lotAreaUnit: "sqft",
      lotAreaValue: 7000.092,
      price: 800,
      state: "TX",
      streetAddress: "5021 Rietta St",
      zipcode: "77016",
      property: "Villa",
    },
    {
      bathrooms: 2,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      imgSrc:
        "https://images.unsplash.com/photo-1560184897-ae75f418493e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      livingArea: 550,
      lotAreaUnit: "sqft",
      lotAreaValue: 7000.092,
      price: 990,
      state: "TX",
      streetAddress: "5021 Rietta St",
      zipcode: "77016",
      property: "Villa",
    },
    {
      bathrooms: 2,
      bedrooms: 6,
      city: "Houston",
      country: "USA",
      currency: "USD",
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      imgSrc:
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      livingArea: 550,
      lotAreaUnit: "sqft",
      lotAreaValue: 7000.092,
      price: 1000,
      state: "TX",
      streetAddress: "5021 Rietta St",
      zipcode: "77016",
      property: "Villa",
    },
    {
      name: "Palm Harbour",
      bathrooms: 1,
      bedrooms: 1,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/deda5975003d18502a1c4a300859fe72-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.850637,
      listing_sub_type: {
        is_FSBA: true,
        property: "Villa",
      },
      livingArea: 550,
      longitude: -95.31703,
      lotAreaUnit: "sqft",
      lotAreaValue: 7000.092,
      price: 1000,
      priceForHDP: 118000,
      rentZestimate: 895,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "5021 Rietta St",
      taxAssessedValue: 57453,
      zestimate: 87600,
      zipcode: "77016",
      zpid: 80530706,
      property: "Villa",
      postMessage: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 4,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/256d952b28528d70443e7287fd6d23a6-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.590986,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 2686,
      longitude: -95.47756,
      lotAreaUnit: "sqft",
      lotAreaValue: 5372,
      price: 1500,
      priceForHDP: 299000,
      rentZestimate: 1950,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "6202 Presidio Dr",
      taxAssessedValue: 294580,
      zestimate: 278600,
      zipcode: "77053",
      zpid: 27545401,
      property: "Villa",
      postedBy: "owner",
    },
    {
      bathrooms: 1,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      datePriceChanged: 1676275200000,
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/15125105644defa17676ea0d37205040-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.699047,
      listing_sub_type: {
        is_FSBA: true,
        property: "villa",
      },
      livingArea: 1194,
      longitude: -95.24173,
      lotAreaUnit: "sqft",
      lotAreaValue: 6268.284,
      price: 1700,
      priceChange: -5000,
      priceForHDP: 189000,
      priceReduction: "$5,000 (Feb 13)",
      rentZestimate: 1399,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "211 Axilda St",
      taxAssessedValue: 150458,
      zestimate: 189200,
      zipcode: "77017",
      zpid: 27955996,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 2,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "CONDO",
      imgSrc:
        "https://photos.zillowstatic.com/fp/4945b079f628751d901b62b22aea3b08-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.78076,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1797,
      longitude: -95.372025,
      newConstructionType: "NEW_CONSTRUCTION_TYPE_OTHER",
      price: 2900,
      priceForHDP: 806122,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "2520 Houston Ave #809B",
      unit: "# 809B",
      zipcode: "77009",
      zpid: 2059143112,
      property: "House",
      postedBy: "agent",
    },
    {
      bathrooms: 3,
      bedrooms: 2,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/88e4f7e4cd49aad48e87f1c4999b8af1-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.83611,
      listing_sub_type: {
        is_FSBA: true,
        property: "House",
        postedBy: "owner",
      },
      livingArea: 1201,
      longitude: -95.54731,
      lotAreaUnit: "sqft",
      lotAreaValue: 3149.388,
      price: 2300,
      priceForHDP: 240000,
      rentZestimate: 1649,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4518 Stanford Ct",
      taxAssessedValue: 82861,
      zestimate: 234300,
      zipcode: "77041",
      zpid: 28210580,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/54e77b713b595e94ffe79f3883e5f3c2-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.678263,
      listing_sub_type: {
        is_FSBA: true,
        property: "House",
        postedBy: "owner",
      },
      livingArea: 2156,
      longitude: -95.45339,
      lotAreaUnit: "sqft",
      lotAreaValue: 8498.556,
      price: 2500,
      priceForHDP: 599900,
      rentZestimate: 2600,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "9610 Cliffwood Dr",
      taxAssessedValue: 202732,
      zestimate: 342300,
      zipcode: "77096",
      zpid: 28041849,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 4,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/442404569fe9cbc88760e472dba1d7ce-p_e.jpg",
      longitude: -95.67195,
      lotAreaUnit: "sqft",
      lotAreaValue: 9744.372,
      price: 999,
      priceForHDP: 399999,
      rentZestimate: 2600,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "11419 Pampass Pass",
      taxAssessedValue: 417908,
      zestimate: 409400,
      zipcode: "77095",
      zpid: 55481406,
    },
    {
      bathrooms: 1,
      bedrooms: 2,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/044de36cc0317545c252e38ee9919e52-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.739561,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 1208,
      longitude: -95.33043,
      lotAreaUnit: "sqft",
      lotAreaValue: 4552.02,
      price: 1699,
      priceForHDP: 425000,
      rentZestimate: 1500,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4607 Park Dr",
      taxAssessedValue: 305045,
      zestimate: 301300,
      zipcode: "77023",
      zpid: 27750600,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/e142e8ae5c822af7f92e4e4dbb35c4e1-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2177,
      lotAreaUnit: "sqft",
      lotAreaValue: 1675,
      newConstructionType: "BUILDER_SPEC",
      price: 2750,
      priceForHDP: 479900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "948 Fisher St #C",
      unit: "# C",
      zipcode: "77018",
      zpid: 2067027712,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/7404fbb4ca2c1ab5de4226b9f92696df-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2177,
      lotAreaUnit: "sqft",
      lotAreaValue: 1676,
      newConstructionType: "BUILDER_SPEC",
      price: 3500,
      priceForHDP: 479900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "950 Fisher Dr #D",
      unit: "# D",
      zipcode: "77018",
      zpid: 2067027703,
    },
    {
      bathrooms: 0,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "LOT",
      imgSrc:
        "https://photos.zillowstatic.com/fp/6dc38d5ffa557dea0398c379217b612e-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.71695,
      listing_sub_type: {
        is_FSBA: true,
      },
      longitude: -95.310844,
      lotAreaUnit: "acres",
      lotAreaValue: 0.5788,
      price: 3200,
      priceForHDP: 888000,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "0 Sylvan Rd",
      zipcode: "77023",
      zpid: 2059143756,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/016b637b10eec3d95bb0d4ceb5a41ee9-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2177,
      lotAreaUnit: "sqft",
      lotAreaValue: 1968,
      newConstructionType: "BUILDER_SPEC",
      price: 3300,
      priceForHDP: 509900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "948 Fisher St #F",
      unit: "# F",
      zipcode: "77018",
      zpid: 2067027716,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      datePriceChanged: 1669104000000,
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/016b637b10eec3d95bb0d4ceb5a41ee9-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.82322,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2177,
      longitude: -95.423325,
      lotAreaUnit: "sqft",
      lotAreaValue: 2020,
      newConstructionType: "BUILDER_SPEC",
      price: 3400,
      priceChange: 5000,
      priceForHDP: 499900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "948 Fisher St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2067027709,
    },
    {
      bathrooms: 3,
      bedrooms: 4,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/d32eeab68f3b60d6e03c63a52495913f-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.954542,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 2777,
      longitude: -95.17855,
      lotAreaUnit: "sqft",
      lotAreaValue: 3868.128,
      price: 3680,
      priceForHDP: 368000,
      rentZestimate: 2127,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "12923 Pecan Shores Dr",
      taxAssessedValue: 339638,
      zestimate: 358186,
      zipcode: "77044",
      zpid: 123232505,
    },
    {
      bathrooms: 2,
      bedrooms: 3,
      city: "Humble",

      country: "USA",
      currency: "USD",
      daysOnZillow: -1,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/2fe2cdddd924676c0e71dd05ade6edb7-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.787493,
      listing_sub_type: {
        is_FSBA: true,
        is_openHouse: true,
      },
      livingArea: 1680,
      longitude: -95.352516,
      lotAreaUnit: "sqft",
      lotAreaValue: 6250.86,
      openHouse: "Sat. 11am-2pm",
      open_house_info: {
        open_house_showing: [
          {
            open_house_end: 1676757600000,
            open_house_start: 1676746800000,
          },
          {
            open_house_end: 1676851200000,
            open_house_start: 1676844000000,
          },
        ],
      },
      price: 3999,
      priceForHDP: 399999,
      rentZestimate: 2250,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "1511 McNeil St",
      taxAssessedValue: 330079,
      zestimate: 391607,
      zipcode: "77009",
      zpid: 27776100,
      property: "Villa",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 700,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 700,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/751169960de668acd5e85e9b59094478-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 1900,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/21141fdcf64badd1ea81cf06f40d82ef-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.831608,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      longitude: -95.40235,
      lotAreaUnit: "sqft",
      lotAreaValue: 1556,
      newConstructionType: "BUILDER_SPEC",
      price: 5900,
      priceForHDP: 395900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #E",
      unit: "# E",
      zestimate: 387600,
      zipcode: "77018",
      zpid: 2065712138,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/21141fdcf64badd1ea81cf06f40d82ef-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1541,
      lotAreaUnit: "sqft",
      lotAreaValue: 1574,
      newConstructionType: "BUILDER_SPEC",
      price: 4000,
      priceForHDP: 405900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4512 Old Yale St #D",
      unit: "# D",
      zipcode: "77018",
      zpid: 2065712188,
    },
    {
      bathrooms: "3",
      bedrooms: "4",
      city: "Humble",
      currency: "USD",
      country: "USA",
      imgSrc:
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80",
      price: 1400,
      lotAreaUnit: "sqft",
      lotAreaValue: 6899.904,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 2,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/fb52ff7e4254b5e6c1c08c9a2c92a1ca-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 30.064821,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 1935,
      longitude: -95.23262,
      lotAreaUnit: "sqft",
      lotAreaValue: 6899.904,
      price: 5000,
      priceForHDP: 305000,
      rentZestimate: 2016,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "26032 Castle Meadow Ln",
      taxAssessedValue: 217170,
      zestimate: 300642,
      zipcode: "77339",
      zpid: 70346518,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/fc1b5caef98cb41290bf2bbd9a31cdca-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.831411,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1541,
      longitude: -95.40238,
      lotAreaUnit: "sqft",
      lotAreaValue: 1554,
      newConstructionType: "BUILDER_SPEC",
      price: 3900,
      priceForHDP: 389900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4512 Old Yale St #B",
      unit: "# B",
      zipcode: "77018",
      zpid: 2065712165,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/78eb68c2dc09376eb857f88b80c02c9c-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1463,
      lotAreaUnit: "sqft",
      lotAreaValue: 1463,
      newConstructionType: "BUILDER_SPEC",
      price: 800,
      priceForHDP: 379900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4510 Old Yale St #B",
      unit: "# B",
      zestimate: 371100,
      zipcode: "77018",
      zpid: 2065712102,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Newyork",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/751169960de668acd5e85e9b59094478-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1541,
      lotAreaUnit: "sqft",
      lotAreaValue: 1554,
      newConstructionType: "BUILDER_SPEC",
      price: 700,
      priceForHDP: 389900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4512 Old Yale St #A",
      unit: "# A",
      zestimate: 381200,
      zipcode: "77018",
      zpid: 2065712163,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Boston",
      country: "USA",
      currency: "USD",
      datePriceChanged: 1666854000000,
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/78eb68c2dc09376eb857f88b80c02c9c-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1546,
      newConstructionType: "BUILDER_SPEC",
      price: 1900,
      priceChange: -5100,
      priceForHDP: 389900,
      priceReduction: "",
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #D",
      unit: "# D",
      zipcode: "77018",
      zpid: 2065712143,
    },
    {
      bathrooms: 4,
      bedrooms: 4,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/5aa085bd07cf082668a4f738661d721b-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 30.019377,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 3092,
      longitude: -95.46587,
      lotAreaUnit: "sqft",
      lotAreaValue: 9513.504,
      price: 4200,
      priceForHDP: 399000,
      rentZestimate: 2799,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "1911 Big Horn Dr",
      taxAssessedValue: 332853,
      zestimate: 383943,
      zipcode: "77090",
      zpid: 28159919,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      datePriceChanged: 1666854000000,
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/78eb68c2dc09376eb857f88b80c02c9c-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1463,
      lotAreaUnit: "sqft",
      lotAreaValue: 1463,
      newConstructionType: "BUILDER_SPEC",
      price: 3699,
      priceChange: -16000,
      priceForHDP: 369900,
      priceReduction: "",
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4510 Old Yale St #C",
      unit: "# C",
      zipcode: "77018",
      zpid: 2065712083,
    },
    {
      bathrooms: 2,
      bedrooms: 0,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/51179ba157362ad731fdb90c736d8e1f-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.883427,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 1986,
      longitude: -95.28974,
      lotAreaUnit: "sqft",
      lotAreaValue: 7318.08,
      price: 4500,
      priceForHDP: 190000,
      rentZestimate: 1795,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "11306 Spottswood Dr",
      taxAssessedValue: 171512,
      zestimate: 170500,
      zipcode: "77016",
      zpid: 28054683,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/07aefa285cc0961da3419d4d1552e165-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.892178,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 2312,
      longitude: -95.67219,
      lotAreaUnit: "sqft",
      lotAreaValue: 8028.108,
      price: 4300,
      priceForHDP: 359900,
      rentZestimate: 2250,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "17343 Meadow Heights Dr",
      taxAssessedValue: 289418,
      zestimate: 359900,
      zipcode: "77095",
      zpid: 28506349,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/f9333502d93778a851ab90514da7c61d-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1951,
      lotAreaUnit: "sqft",
      lotAreaValue: 1980,
      newConstructionType: "BUILDER_SPEC",
      price: 4390,
      priceForHDP: 434900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "903 Lehman St #F",
      unit: "# F",
      zipcode: "77018",
      zpid: 2066875807,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/6449d4166f799980c2f814b406c1c581-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1857,
      lotAreaUnit: "sqft",
      lotAreaValue: 1472,
      newConstructionType: "BUILDER_SPEC",
      price: 4900,
      priceForHDP: 424900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4969 Brinkman St",
      zipcode: "77018",
      zpid: 2066876124,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/47b66750596d26184b6434538b175d2a-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.838493,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1951,
      longitude: -95.41691,
      lotAreaUnit: "sqft",
      lotAreaValue: 1980,
      newConstructionType: "BUILDER_SPEC",
      price: 4340,
      priceForHDP: 434900,
      rentZestimate: 2827,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "903 Lehman St",
      taxAssessedValue: 173865,
      zipcode: "77018",
      zpid: 27797543,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "TOWNHOUSE",
      imgSrc:
        "https://photos.zillowstatic.com/fp/789b41ab395c9f425d67e34d73c1ddcd-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.75153,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 2337,
      longitude: -95.38031,
      lotAreaUnit: "sqft",
      lotAreaValue: 1622,
      price: 4000,
      priceForHDP: 495000,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "150 Oak Place Dr",
      zipcode: "77006",
      zpid: 2059143975,
    },
    {
      bathrooms: 3,
      bedrooms: 4,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/b63c18a22c367834fede764a1d28e1a8-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.701794,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 4000,
      longitude: -95.565865,
      lotAreaUnit: "sqft",
      lotAreaValue: 3981.384,
      price: 3700,
      priceForHDP: 450000,
      rentZestimate: 2165,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "6895 Turtlewood Dr",
      taxAssessedValue: 328808,
      zestimate: 450000,
      zipcode: "77072",
      zpid: 84023913,
      property: "villa",
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/2fbfbd4597a56f19e67e7a0be37945ac-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.802755,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2350,
      longitude: -95.51068,
      newConstructionType: "BUILDER_SPEC",
      price: 1800,
      priceForHDP: 464990,
      rentZestimate: 1463,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "8908 Covenant Pl",
      taxAssessedValue: 134700,
      zipcode: "77055",
      zpid: 337097091,
    },
    {
      bathrooms: 2,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/b4f5ad1398197c6ad3ec66bdd7edf53e-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.56327,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 1648,
      longitude: -95.10672,
      lotAreaUnit: "sqft",
      lotAreaValue: 7501.032,
      price: 1500,
      priceForHDP: 250000,
      rentZestimate: 1990,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "16810 Ashmoor Way",
      taxAssessedValue: 264378,
      zestimate: 247600,
      zipcode: "77058",
      zpid: 28329094,
    },
    {
      bathrooms: 1,
      bedrooms: 2,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/67e42d7f1680c4d336b461012673216c-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.79812,
      listing_sub_type: {
        is_FSBA: true,
      },
      livingArea: 800,
      longitude: -95.40376,
      lotAreaUnit: "sqft",
      lotAreaValue: 2901.096,
      price: 4900,
      priceForHDP: 499900,
      rentZestimate: 1800,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "1501 Ashland St",
      taxAssessedValue: 278075,
      zestimate: 424700,
      zipcode: "77008",
      zpid: 27760502,
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/2fbfbd4597a56f19e67e7a0be37945ac-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2350,
      newConstructionType: "BUILDER_SPEC",
      price: 3000,
      priceForHDP: 464990,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "8902 Covenant Pl",
      zipcode: "77055",
      zpid: 2059144163,
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 900,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 2500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 1500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 3500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "Villa",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 900,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 2500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 1500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 900,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 700,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 3100,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Humble",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 3500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 900,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2074&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 700,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 3100,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },

    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Houston",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 2500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 3,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 1554,
      lotAreaUnit: "sqft",
      lotAreaValue: 1547,
      newConstructionType: "BUILDER_SPEC",
      price: 3500,
      priceForHDP: 399900,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "4514 Old Yale St #A",
      unit: "# A",
      zipcode: "77018",
      zpid: 2065712152,
      property: "House",
      postedBy: "owner",
    },
    {
      bathrooms: 4,
      bedrooms: 3,
      city: "Seattle",
      country: "USA",
      currency: "USD",
      daysOnZillow: 0,
      homeStatus: "FOR_SALE",
      homeStatusForHDP: "FOR_SALE",
      homeType: "SINGLE_FAMILY",
      imgSrc:
        "https://photos.zillowstatic.com/fp/b37e76b4aef8a69ca2886bcbea7ea335-p_e.jpg",
      isFeatured: false,
      isNonOwnerOccupied: true,
      isPreforeclosureAuction: false,
      isPremierBuilder: false,
      isUnmappable: false,
      isZillowOwned: false,
      latitude: 29.812088,
      listing_sub_type: {
        is_newHome: true,
      },
      livingArea: 2265,
      longitude: -95.38169,
      lotAreaUnit: "sqft",
      lotAreaValue: 1464,
      newConstructionType: "BUILDER_SPEC",
      price: 1200,
      priceForHDP: 519900,
      rentZestimate: 2999,
      shouldHighlight: false,
      state: "TX",
      streetAddress: "1303 E 27th St UNIT B",
      unit: "Unit B",
      zestimate: 509700,
      zipcode: "77009",
      zpid: 2114572433,
    },
  ],
  resultsPerPage: 40,
  totalPages: 20,
  totalResultCount: 7975,
};
